export const progressPoseComparisonConfig = {
  minimumLandmarkConfidence: 0.2,
  minimumCommonLandmarkCount: 6,
  minimumCommonTorsoLandmarkCount: 3,
  relativeLandmarkDistanceTolerance: 0.65,
  jointAngleDifferenceToleranceRadians: Math.PI / 2,
  framingPositionTolerance: 0.25,
  framingScaleRatioTolerance: 1.5,
  framingRotationToleranceRadians: (20 * Math.PI) / 180,
  movementInstructionThreshold: 0.035,
  scaleInstructionRatioThreshold: 1.08,
  rotationInstructionThresholdRadians: (4 * Math.PI) / 180,
  adjustPoseInstructionThreshold: 0.82,
  stabilityThresholds: {
    pose: 0.82,
    framing: 0.78,
    visibility: 0.65,
    overall: 0.8,
  },
  scoreWeights: {
    relativeLandmarks: 0.65,
    jointAngles: 0.35,
    framingPosition: 0.45,
    framingScale: 0.4,
    framingRotation: 0.15,
    overallPose: 0.55,
    overallFraming: 0.3,
    overallVisibility: 0.15,
  },
} as const;
